"""AutoresearchIterator — Karpathy-style learning loop for trading execution.

Runs every 30 minutes (not daily — compressed for faster improvement loops).

Evaluates execution quality on these dimensions:
  1. Sizing alignment — was position size proportional to conviction at the time?
  2. Stop quality — was the stop hit because thesis was wrong, or weekend wick / noise?
  3. Funding efficiency — was carry cost worth the return?
  4. Catalyst timing — were deleverage actions timely?

CRITICAL EXTENSION over vanilla Karpathy:
  - Multi-source evidence weighting: tracks which news sources are most predictive
  - Causal attribution: distinguishes thesis invalidation from noise exits
    (a SL hit on Saturday wick → reduce weekend leverage, NOT thesis conviction)
  - Reflexivity tracking: notes when winning positions created their own momentum

Writes to:
  data/research/evaluations/YYYY-MM-DD_HHMMSS.json  (full evaluation)
  data/research/learnings.md                          (human-readable log for AI to read)

The scheduled task reads learnings.md to inform next conviction assessment.
"""
from __future__ import annotations

import json
import logging
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

from cli.daemon.context import TickContext

log = logging.getLogger("daemon.autoresearch")

EVAL_INTERVAL_S = 1800          # 30 minutes (compressed from daily for faster loops)
EVAL_DIR = "data/research/evaluations"
LEARNINGS_FILE = "data/research/learnings.md"
JOURNAL_FILE = "data/daemon/journal.jsonl"     # daemon journal for trade history
FUNDING_FILE = "data/daemon/funding_tracker.jsonl"


def _parse_ts(ts_str: str) -> int:
    """Parse ISO timestamp string to epoch milliseconds."""
    if not ts_str:
        return 0
    try:
        from datetime import datetime, timezone
        # Handle "2026-04-06T12:00:00Z" format
        dt = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
        return int(dt.timestamp() * 1000)
    except Exception:
        return 0


@dataclass
class EvaluationResult:
    """Structured result of one autoresearch cycle."""
    timestamp: int
    timestamp_human: str

    # Sizing quality
    sizing_alignment_score: float = 0.0   # 0-1: was sizing proportional to conviction?
    sizing_notes: str = ""

    # Stop quality (causal attribution — key differentiator from vanilla Karpathy)
    stops_evaluated: int = 0
    stops_thesis_invalidation: int = 0    # correct to stop
    stops_noise_exit: int = 0             # weekend wicks, stop hunts (should improve)
    stop_quality_notes: str = ""

    # Funding efficiency
    funding_paid_usd: float = 0.0
    funding_earned_usd: float = 0.0
    funding_efficiency_score: float = 0.0  # 0-1
    funding_notes: str = ""

    # Catalyst timing
    catalyst_timing_score: float = 0.0
    catalyst_notes: str = ""

    # Evidence source quality
    source_accuracy: Dict[str, float] = field(default_factory=dict)  # source -> hit rate

    # Reflexivity signals
    reflexivity_notes: str = ""

    # Overall
    overall_score: float = 0.0
    recommendations: List[str] = field(default_factory=list)
    raw_data: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict:
        return {
            "timestamp": self.timestamp,
            "timestamp_human": self.timestamp_human,
            "sizing_alignment_score": self.sizing_alignment_score,
            "sizing_notes": self.sizing_notes,
            "stops_evaluated": self.stops_evaluated,
            "stops_thesis_invalidation": self.stops_thesis_invalidation,
            "stops_noise_exit": self.stops_noise_exit,
            "stop_quality_notes": self.stop_quality_notes,
            "funding_paid_usd": self.funding_paid_usd,
            "funding_earned_usd": self.funding_earned_usd,
            "funding_efficiency_score": self.funding_efficiency_score,
            "funding_notes": self.funding_notes,
            "catalyst_timing_score": self.catalyst_timing_score,
            "catalyst_notes": self.catalyst_notes,
            "source_accuracy": self.source_accuracy,
            "reflexivity_notes": self.reflexivity_notes,
            "overall_score": self.overall_score,
            "recommendations": self.recommendations,
        }


class AutoresearchIterator:
    """Runs periodic execution quality evaluations and writes learnings for the AI to read."""

    name = "autoresearch"

    def __init__(self):
        self._last_eval: float = 0.0
        self._session_start = time.time()

    def on_start(self, ctx: TickContext) -> None:
        Path(EVAL_DIR).mkdir(parents=True, exist_ok=True)
        Path(LEARNINGS_FILE).parent.mkdir(parents=True, exist_ok=True)
        if not os.path.exists(LEARNINGS_FILE):
            with open(LEARNINGS_FILE, "w") as f:
                f.write("# Trading Execution Learnings\n\n"
                        "Auto-generated by autoresearch loop. "
                        "AI reads this file each evaluation cycle to improve conviction assessments.\n\n")
        log.info("AutoresearchIterator started  eval_interval=%ds", EVAL_INTERVAL_S)

    def on_stop(self) -> None:
        pass

    def tick(self, ctx: TickContext) -> None:
        now = time.monotonic()
        if now - self._last_eval < EVAL_INTERVAL_S:
            return
        self._last_eval = now
        self._run_evaluation(ctx)

    def _run_evaluation(self, ctx: TickContext) -> None:
        """Run one evaluation cycle."""
        ts = int(time.time() * 1000)
        ts_human = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
        log.info("AutoresearchIterator: running evaluation at %s", ts_human)

        result = EvaluationResult(timestamp=ts, timestamp_human=ts_human)

        # --- Sizing alignment ---
        self._evaluate_sizing(result, ctx)

        # --- Stop quality (causal attribution) ---
        self._evaluate_stops(result, ctx)

        # --- Funding efficiency ---
        self._evaluate_funding(result, ctx)

        # --- Catalyst timing ---
        self._evaluate_catalyst_timing(result, ctx)

        # --- Evidence source quality ---
        self._evaluate_source_quality(result, ctx)

        # --- Overall score ---
        scores = [
            result.sizing_alignment_score,
            result.funding_efficiency_score,
            result.catalyst_timing_score,
        ]
        result.overall_score = sum(s for s in scores if s > 0) / max(len([s for s in scores if s > 0]), 1)

        # --- Write evaluation ---
        self._save_evaluation(result)

        # --- Append to learnings.md ---
        self._append_learning(result, ctx)

        # --- REFLECT: analyze closed trades for performance metrics ---
        self._run_reflect(result, ctx)

        log.info("Autoresearch: overall_score=%.2f  recs=%d",
                 result.overall_score, len(result.recommendations))

    def _evaluate_sizing(self, result: EvaluationResult, ctx: TickContext) -> None:
        """Was position size proportional to thesis conviction?"""
        if not ctx.thesis_states:
            result.sizing_notes = "No thesis states available — cannot evaluate sizing"
            result.sizing_alignment_score = 0.5  # neutral
            return

        issues = []
        scores = []
        for market, thesis in ctx.thesis_states.items():
            conviction = thesis.effective_conviction()
            current_pos = None
            for pos in ctx.positions:
                if market in pos.instrument or pos.instrument in market:
                    current_pos = pos
                    break

            if current_pos is None:
                if conviction > 0.5:
                    issues.append(f"{market}: conviction {conviction:.2f} but no position — missed entry?")
                continue

            account_equity = float(ctx.balances.get("USDC", 0))
            if account_equity <= 0:
                continue

            price = float(ctx.prices.get(market, 0))
            if price <= 0:
                continue

            current_notional = abs(float(current_pos.net_qty)) * price
            current_pct = current_notional / account_equity

            # Expected range based on conviction band
            if conviction >= 0.8:
                expected_min, expected_max = 0.15, 0.25
            elif conviction >= 0.5:
                expected_min, expected_max = 0.08, 0.16
            elif conviction >= 0.2:
                expected_min, expected_max = 0.03, 0.09
            else:
                expected_min, expected_max = 0.0, 0.02

            if current_pct < expected_min:
                issues.append(f"{market}: undersized — {current_pct:.1%} vs expected {expected_min:.1%}-{expected_max:.1%} at conviction {conviction:.2f}")
                scores.append(0.5)
            elif current_pct > expected_max:
                issues.append(f"{market}: oversized — {current_pct:.1%} vs expected {expected_min:.1%}-{expected_max:.1%} at conviction {conviction:.2f}")
                scores.append(0.6)
            else:
                scores.append(1.0)

        if scores:
            result.sizing_alignment_score = sum(scores) / len(scores)
        else:
            result.sizing_alignment_score = 0.5

        if issues:
            result.sizing_notes = "; ".join(issues)
            result.recommendations.extend(issues)
        else:
            result.sizing_notes = "Sizing aligned with conviction levels"

    def _evaluate_stops(self, result: EvaluationResult, ctx: TickContext) -> None:
        """Evaluate stop quality using causal attribution (key extension over Karpathy)."""
        try:
            journal_entries = self._load_recent_journal(hours=1)
        except Exception:
            result.stop_quality_notes = "No journal data available"
            return

        stop_exits = [e for e in journal_entries if e.get("action") in ("stop_triggered", "sl_hit", "close")]
        result.stops_evaluated = len(stop_exits)

        thesis_invalidations = 0
        noise_exits = 0

        for exit_ev in stop_exits:
            # Heuristic: was this exit on a weekend? Was price action extreme?
            ts = exit_ev.get("timestamp", 0)
            dt = time.gmtime(ts / 1000) if ts > 0 else time.gmtime()
            weekday = dt.tm_wday   # 0=Mon

            exit_cause = exit_ev.get("exit_cause", "unknown")

            if exit_cause == "thesis_invalidation":
                thesis_invalidations += 1
            elif exit_cause in ("weekend_wick", "noise", "stop_hunt"):
                noise_exits += 1
            elif weekday in (5, 6):  # Saturday or Sunday
                # Exit on weekend → likely noise/stop hunt
                noise_exits += 1
                log.info("Autoresearch: weekend exit detected — likely stop hunt, not thesis")
            else:
                thesis_invalidations += 1

        result.stops_thesis_invalidation = thesis_invalidations
        result.stops_noise_exit = noise_exits

        if noise_exits > thesis_invalidations and result.stops_evaluated > 0:
            result.stop_quality_notes = (
                f"{noise_exits}/{result.stops_evaluated} exits appear to be noise (weekend wicks/stop hunts). "
                "Reduce weekend leverage, not overall conviction."
            )
            result.recommendations.append(
                "STOP QUALITY: More noise exits than thesis exits — reduce weekend leverage to avoid stop hunts"
            )
        elif result.stops_evaluated > 0:
            result.stop_quality_notes = (
                f"{thesis_invalidations}/{result.stops_evaluated} exits were thesis-driven (correct)"
            )

    def _evaluate_funding(self, result: EvaluationResult, ctx: TickContext) -> None:
        """Was carry cost worth the return?"""
        try:
            funding_data = self._load_funding_summary()
            result.funding_paid_usd = funding_data.get("total_paid", 0.0)
            result.funding_earned_usd = funding_data.get("total_earned", 0.0)
            net = result.funding_earned_usd - result.funding_paid_usd

            # Compare to unrealized PnL
            total_upnl = 0.0
            for pos in ctx.positions:
                if pos.net_qty != 0:
                    price = float(ctx.prices.get(pos.instrument, 0))
                    if price > 0:
                        total_upnl += float(pos.unrealized_pnl(pos.avg_entry_price))  # rough estimate

            if abs(result.funding_paid_usd) > 0:
                # Efficiency: how much unrealized gain per dollar of funding paid?
                result.funding_efficiency_score = min(1.0, max(0.0, 0.5 + net / (abs(result.funding_paid_usd) + 0.01) * 0.5))
            else:
                result.funding_efficiency_score = 0.8

            if result.funding_paid_usd > 50:
                result.funding_notes = f"Heavy funding cost: ${result.funding_paid_usd:.2f} paid — monitor position sizing"
                result.recommendations.append(f"FUNDING: ${result.funding_paid_usd:.2f} in costs — consider reducing size during high backwardation")
            else:
                result.funding_notes = f"Funding: paid=${result.funding_paid_usd:.2f}, earned=${result.funding_earned_usd:.2f}"

        except Exception as e:
            result.funding_notes = f"Funding data unavailable: {e}"
            result.funding_efficiency_score = 0.5

    def _evaluate_catalyst_timing(self, result: EvaluationResult, ctx: TickContext) -> None:
        """Were deleverage actions timely relative to catalyst events?"""
        # Read catalyst events from disk
        catalyst_file = "data/daemon/catalyst_events.json"
        if not os.path.exists(catalyst_file):
            result.catalyst_timing_score = 0.5
            result.catalyst_notes = "No catalyst events file"
            return

        try:
            with open(catalyst_file) as f:
                events = json.load(f)

            executed = [e for e in events if e.get("executed")]
            pending = [e for e in events if not e.get("executed")]

            now = time.time()
            overdue = []
            for ev in pending:
                ev_date = ev.get("event_date", "")
                pre_hours = ev.get("pre_event_hours", 24)
                # Parse date
                try:
                    from datetime import datetime
                    ev_ts = datetime.strptime(ev_date, "%Y-%m-%d").timestamp()
                    trigger_ts = ev_ts - pre_hours * 3600
                    if now > trigger_ts:
                        overdue.append(ev.get("name", "unknown"))
                except Exception:
                    pass

            if overdue:
                result.catalyst_timing_score = 0.3
                result.catalyst_notes = f"OVERDUE catalyst deleverages: {overdue}"
                result.recommendations.extend([f"CATALYST: {e} is overdue for deleverage" for e in overdue])
            elif executed:
                result.catalyst_timing_score = 0.9
                result.catalyst_notes = f"{len(executed)} catalyst events handled on time"
            else:
                result.catalyst_timing_score = 0.7
                result.catalyst_notes = f"No catalysts executed yet, {len(pending)} pending"

        except Exception as e:
            result.catalyst_timing_score = 0.5
            result.catalyst_notes = f"Catalyst eval error: {e}"

    def _evaluate_source_quality(self, result: EvaluationResult, ctx: TickContext) -> None:
        """Track which evidence sources (news, fundamentals, price action) are most predictive."""
        # Read thesis states to find evidence sources used
        if not ctx.thesis_states:
            return

        source_counts: Dict[str, int] = {}
        for thesis in ctx.thesis_states.values():
            for ev in thesis.evidence_for + thesis.evidence_against:
                source = ev.source
                source_counts[source] = source_counts.get(source, 0) + 1

        if source_counts:
            result.source_accuracy = {s: 0.5 for s in source_counts}  # baseline; refined over time
            # Fundamentals are more reliable than news for thesis trades
            if "fundamentals" in result.source_accuracy:
                result.source_accuracy["fundamentals"] = 0.8
            if "news" in result.source_accuracy:
                result.source_accuracy["news"] = 0.5  # wartime news unreliable

    def _append_learning(self, result: EvaluationResult, ctx: TickContext) -> None:
        """Append human-readable learning entry for AI to read next evaluation."""
        lines = [
            f"\n## {result.timestamp_human}  (score: {result.overall_score:.2f})\n",
        ]

        if result.sizing_notes:
            lines.append(f"**Sizing:** {result.sizing_notes}\n")

        if result.stops_evaluated > 0:
            lines.append(
                f"**Stops:** {result.stops_evaluated} evaluated — "
                f"{result.stops_thesis_invalidation} thesis-driven, "
                f"{result.stops_noise_exit} noise. {result.stop_quality_notes}\n"
            )

        if result.funding_notes:
            lines.append(f"**Funding:** {result.funding_notes}\n")

        if result.catalyst_notes:
            lines.append(f"**Catalysts:** {result.catalyst_notes}\n")

        if result.recommendations:
            lines.append("**Recommendations:**\n")
            for rec in result.recommendations:
                lines.append(f"- {rec}\n")

        # Active thesis summary
        for market, thesis in ctx.thesis_states.items():
            lines.append(
                f"**Thesis {market}:** direction={thesis.direction}  "
                f"conviction={thesis.conviction:.2f} (effective={thesis.effective_conviction():.2f})  "
                f"age={thesis.age_hours:.1f}h\n"
            )

        try:
            with open(LEARNINGS_FILE, "a") as f:
                f.writelines(lines)
            log.info("Autoresearch: appended learning to %s", LEARNINGS_FILE)
        except Exception as e:
            log.error("Failed to write learnings: %s", e)

    def _save_evaluation(self, result: EvaluationResult) -> None:
        """Save full evaluation JSON."""
        ts_str = time.strftime("%Y-%m-%d_%H%M%S", time.gmtime())
        path = os.path.join(EVAL_DIR, f"{ts_str}.json")
        try:
            with open(path, "w") as f:
                json.dump(result.to_dict(), f, indent=2)
        except Exception as e:
            log.error("Failed to save evaluation: %s", e)

    def _load_recent_journal(self, hours: float = 24) -> List[Dict]:
        """Load recent journal entries."""
        if not os.path.exists(JOURNAL_FILE):
            return []
        cutoff = (time.time() - hours * 3600) * 1000
        entries = []
        try:
            with open(JOURNAL_FILE) as f:
                for line in f:
                    try:
                        e = json.loads(line.strip())
                        if e.get("timestamp", 0) >= cutoff:
                            entries.append(e)
                    except Exception:
                        pass
        except Exception as e:
            log.debug("Journal read error: %s", e)
        return entries

    def _run_reflect(self, result: EvaluationResult, ctx: TickContext) -> None:
        """Run REFLECT engine on recent closed trades from journal JSONL."""
        journal_jsonl = "data/research/journal.jsonl"
        if not os.path.exists(journal_jsonl):
            return

        try:
            from modules.reflect_engine import ReflectEngine, TradeRecord

            # Load journal entries from the last 7 days
            cutoff_ms = (time.time() - 7 * 86400) * 1000
            trades = []
            with open(journal_jsonl) as f:
                for line in f:
                    if not line.strip():
                        continue
                    try:
                        entry = json.loads(line)
                        # Convert journal format to TradeRecord format
                        # Journal has: entry_price, exit_price, direction, size, instrument, pnl
                        # TradeRecord needs: side, price, quantity pairs for FIFO matching
                        # Create synthetic entry + exit trade records
                        entry_price = float(entry.get("entry_price", 0))
                        exit_price = float(entry.get("exit_price", 0))
                        size = float(entry.get("size", 0))
                        direction = entry.get("direction", "LONG").lower()

                        if entry_price <= 0 or exit_price <= 0 or size <= 0:
                            continue

                        # Parse timestamps
                        ts_open = entry.get("timestamp_open", "")
                        ts_close = entry.get("timestamp_close", "")
                        open_ms = _parse_ts(ts_open)
                        close_ms = _parse_ts(ts_close)

                        if close_ms < cutoff_ms:
                            continue

                        entry_side = "buy" if direction == "long" else "sell"
                        exit_side = "sell" if direction == "long" else "buy"

                        trades.append(TradeRecord(
                            instrument=entry.get("instrument", ""),
                            side=entry_side,
                            price=entry_price,
                            quantity=size,
                            timestamp_ms=open_ms,
                        ))
                        trades.append(TradeRecord(
                            instrument=entry.get("instrument", ""),
                            side=exit_side,
                            price=exit_price,
                            quantity=size,
                            timestamp_ms=close_ms,
                            meta=entry.get("close_reason", ""),
                        ))
                    except Exception:
                        continue

            if len(trades) < 2:
                return

            engine = ReflectEngine()
            metrics = engine.compute(trades)

            # Append REFLECT summary to learnings
            reflect_lines = [
                f"\n### REFLECT (7d rolling)\n",
                f"Round trips: {metrics.total_round_trips}  "
                f"Win rate: {metrics.win_rate:.0f}%  "
                f"Net PnL: ${metrics.net_pnl:+.2f}\n",
            ]
            if metrics.total_round_trips > 0:
                reflect_lines.append(
                    f"Gross PnL: ${metrics.gross_pnl:+.2f}  "
                    f"Fees: ${metrics.total_fees:.2f}  "
                    f"FDR: {metrics.fdr:.0f}%\n"
                )
                reflect_lines.append(
                    f"Longs: {metrics.long_count} ({metrics.long_wins}W)  "
                    f"Shorts: {metrics.short_count} ({metrics.short_wins}W)\n"
                )
                if metrics.max_consecutive_losses > 2:
                    reflect_lines.append(
                        f"WARNING: {metrics.max_consecutive_losses} consecutive losses\n"
                    )
                if metrics.recommendations:
                    for rec in metrics.recommendations[:3]:
                        reflect_lines.append(f"- {rec}\n")
                        result.recommendations.append(f"REFLECT: {rec}")

            try:
                with open(LEARNINGS_FILE, "a") as f:
                    f.writelines(reflect_lines)
            except Exception:
                pass

            log.info("REFLECT: %d round trips, %.0f%% WR, $%+.2f net",
                     metrics.total_round_trips, metrics.win_rate, metrics.net_pnl)

        except ImportError:
            log.debug("reflect_engine not available — skipping REFLECT")
        except Exception as e:
            log.warning("REFLECT failed: %s", e)

    def _load_funding_summary(self) -> Dict:
        """Load funding tracker summary."""
        if not os.path.exists(FUNDING_FILE):
            return {}
        total_paid = 0.0
        total_earned = 0.0
        try:
            with open(FUNDING_FILE) as f:
                for line in f:
                    try:
                        e = json.loads(line.strip())
                        cost = float(e.get("cost_usd", 0))
                        if cost > 0:
                            total_paid += cost
                        else:
                            total_earned += abs(cost)
                    except Exception:
                        pass
        except Exception as e:
            log.debug("Funding tracker read error: %s", e)
        return {"total_paid": total_paid, "total_earned": total_earned}
