"""
[STRATEGY NAME] — Generated by OpenClaw Agent
==============================================

This is a generated strategy template. It inherently receives standard tick events 
and outputs StrategyDecisions (which the engine converts to orders).

Usage via CLI:
    hl run [strategy_id] -i [INSTRUMENT] --tick 60
"""
from __future__ import annotations

import logging
from typing import List, Optional

from sdk.strategy_sdk.base import BaseStrategy, StrategyContext
from common.models import MarketSnapshot, StrategyDecision, DecisionType

log = logging.getLogger("strategy.[strategy_id]")


class GeneratedStrategy(BaseStrategy):
    """
    [Describe the strategy logic here]
    """

    def __init__(self, my_param: float = 1.0, **kwargs):
        """
        Initialise custom properties. 
        Always call super().__init__(strategy_id="[strategy_id]")!
        """
        super().__init__(strategy_id="[strategy_id]")
        self.my_param = my_param
        self._is_in_position = False

    def on_tick(
        self,
        snapshot: MarketSnapshot,
        context: Optional[StrategyContext] = None,
    ) -> List[StrategyDecision]:
        """
        Called every tick by the daemon core.
        
        Args:
            snapshot: Latest market price, mid, spread.
            context: Holds proxy, state, data cache, etc.
        """
        decisions: List[StrategyDecision] = []

        # Example Data Access: Use the context proxy to get recent candles
        if context and context.meta:
            proxy = context.meta.get("proxy") or context.meta.get("hl_proxy")
            if proxy:
                # Get historical 1-minute candles for indicator math (e.g., Bollinger Bands)
                # candles = proxy.get_candles(snapshot.instrument, interval="1m", lookback_ms=1000*60*60)
                pass

        # Strategy Logic here...
        # ...
        
        # Example Buy Generation
        # decisions.append(StrategyDecision(
        #     type=DecisionType.ENTER_LONG,
        #     instrument=snapshot.instrument,
        #     confidence=0.85,
        #     size_usd=100.0,
        #     reason="Price crossed SMA"
        # ))

        return decisions
